-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 21:51:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_scn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_scn` DEFAULT CHARACTER SET utf8 ;
USE `db_scn` ;

-- -----------------------------------------------------
-- Table `db_scn`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scn`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(15) NULL,
  `cargo` VARCHAR(45) NOT NULL DEFAULT '\"comum\"',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_scn`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scn`.`noticia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `jornalista` VARCHAR(45) NOT NULL,
  `texto` TEXT NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_scn`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_scn`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `texto` TEXT NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `like` INT UNSIGNED NOT NULL,
  `dislike` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_usuario_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_scn`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
